/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ksh;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AppTest {
    // @Test
    // void appHasAGreeting() {
    //     final App classUnderTest = new App();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }

    // @Test
    // void contextLoads() {
    // }
}
