// TODO: global uncaught exception handler

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ksh;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(final String[] args) {
        System.out.println(new App().getGreeting());
    }
}
